# Generated by Django 4.2.1 on 2023-05-18 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaytmDataBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=150, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('checksumhash', models.CharField(max_length=255)),
                ('txn_id', models.CharField(max_length=100)),
            ],
        ),
    ]
